name: Auto Sync n8n-advanced with Upstream
on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/n8n-io/n8n.git || true
          git fetch upstream
          
      - name: Force sync with upstream
        run: |
          git reset --hard upstream/master
          git push --force-with-lease
          
      - name: Sync releases
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/n8n-io/n8n/releases/latest | jq -r '.tag_name')
          gh release delete "$LATEST_RELEASE" --repo "$GITHUB_REPOSITORY" -y 2>/dev/null || true
          gh release create "$LATEST_RELEASE" \
            --repo "$GITHUB_REPOSITORY" \
            --title "n8n-advanced Release $LATEST_RELEASE" \
            --notes "Auto-sync von n8n upstream" \
            --latest || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}